### ISSUE TITLE
Improve main hamburger menu

### ISSUE THREAD

**Issue by ttowntom** [NoroffFEU/yeetsheet#129]
- Add overlay to all other body elements, such that the hamburger menu stands out
- Add event listener to close the menu when a user clicks outside it (it akready closes when clicking the icon agian - see if you can use the same close function in the event listener)

Make sure PR #127 is merged before you start work on this task.

**Comment by martinsk91** [comment]
The menu alredy closes from the showDropdownMenu function in the menu.mjs file.

**Comment by jonhenrikaavitsland** [comment]
@DanielEkerhovd It seems this ticket has already been completed through the work of a different ticket.
