### ISSUE TITLE
Improve Dark Mode Toggle: Consistent Error Handling and Theme Management

### ISSUE THREAD

**Issue by FredrikMohag** [NoroffFEU/yeetsheet#135]
The current dark mode toggle functionality can be improved for better consistency and error handling. 
Suggested improvements include:

1. Throw errors if elements (#darkModeToggleBtn, .toggle-text) are missing to aid in debugging.

2. Consistent use of localStorage by storing both "light" and "dark" themes, instead of removing the key for dark mode.

3. Add aria-pressed attribute to the toggle button for better accessibility.

4. Refactor to reduce duplicate DOM manipulations and improve readability.

Implementing these changes will make the toggle more robust and user-friendly.

**Comment by MandeepKS** [comment]
Task has been completed. Send further to review.

**Comment by FredrikMohag** [comment]
@MandeepKS do you have the PR for these improvements?

**Comment by Barvand** [comment]
@MandeepKS Hi Mandeep, could you link the Pull request?

**Comment by MandeepKS** [comment]
I pushed into mandeep workflow branch, i d'nt think i took PR from main branch after that.

**Comment by FredrikMohag** [comment]
Okey so the problem now is that I can’t see your improvements. I can’t see your changes in the Workflow branch so that’s why it’s important that you make a branch for me so I can do a quality control. 

So it’s only me or @Barvand  that can merge a PR. 

It’s fine for this time, because it was me that opened this “issue”

**Comment by Barvand** [comment]
I have created a pull request for this #262 and will be merging it now.

**Comment by Barvand** [comment]
Please in the future, create a branch name related to the feature you are building and create a pull request. Nonetheless good job @MandeepKS
