### ISSUE TITLE
Display number of the cell in code editor (left button) when the cell is clicked

### ISSUE THREAD

**Issue by Barvand** [NoroffFEU/yeetsheet#148]
Hi Lily, 

Check #35. This function has been overwritten by another commit. 
We should implement it again. You can create a new branch and start creating the code for the function.

**Comment by thislily** [comment]
Hi guys, I think the issue was literally that the cell was not labelled with an id in the html. Seems to work fine now? https://github.com/NoroffFEU/yeetsheet/pull/177

**Comment by FredrikMohag** [comment]
Can you double check that was the case @Barvand

**Comment by Barvand** [comment]
@FredrikMohag Yea this is exactly how it is suppose to look! 

@thislily Good job Lily! 

I see that you have merged the branch into workflow @FredrikMohag Awesome job!
