### ISSUE TITLE
Add Figma files to documentation

### ISSUE THREAD

**Issue by ttowntom** [NoroffFEU/yeetsheet#153]
- [Overview and styleguide](https://www.figma.com/design/N7DYyZAfMzCrilVug7oiYz/Prototype)
- [Prototype](https://www.figma.com/proto/N7DYyZAfMzCrilVug7oiYz/Prototype?page-id=0%3A1&node-id=744-3142&node-type=frame&viewport=274%2C121%2C0.08&t=bXgmJdlDiYRKeBCq-1&scaling=min-zoom&content-scaling=fixed)

**Comment by ttowntom** [comment]
@aklevjer 
The design is currently hosted by Henrik. He's told me that he plans to remove the design from his plan after the semester. Therefore it would be better to declare the link to the [Figma zip-file](https://github.com/user-attachments/files/15737642/Prototype.files.zip) in the documentation.

**Comment by aklevjer** [comment]
@ttowntom
Thank you for the heads-up! I'll update the documentation to include the link to the Figma zip file as suggested.

**Comment by jonhenrikaavitsland** [comment]
@aklevjer thank you, the ticket has now been closed.
