### ISSUE TITLE
Change the appearance of the mobile hamburger menu and close the menu by clicking on the outside/window - js

### ISSUE THREAD

**Issue by renahashimi** [NoroffFEU/yeetsheet#156]

**Comment by ttowntom** [comment]
Heads up:
This ticket looks like it might interfer with [another one](https://github.com/NoroffFEU/yeetsheet/issues/129)

If all changes in the mentioned ticket have been fixed in PR #181 , please delete Issue #129 .

**Comment by jonhenrikaavitsland** [comment]
@RamonaXR Requesting your assistance please.

**Comment by RamonaXR** [comment]
Ok. I am ready.

**Comment by RamonaXR** [comment]
@jonhenrikaavitsland These merge conflicts are too difficult for me to handle alone

**Comment by jonhenrikaavitsland** [comment]
@RamonaXR Ok, thank you for the attempt.

**Comment by jonhenrikaavitsland** [comment]
@renahashimi the PR was merged successfully. 
This ticket is now closed. 
Good work.
thank you. :)
