### ISSUE TITLE
add functinality to change project name

### ISSUE THREAD

**Issue by jonhenrikaavitsland** [NoroffFEU/yeetsheet#159]

**Comment by jonhenrikaavitsland** [comment]
@TGBAKC for your next task, assign your self to the Assignees slot on thr right side of this card.
Every card is the same. 

And then when you create a PR you would want to request a review from me, you can add my name from within the PR. 
This ticket iwll be processed tomorrow. Thank you for the headsup.

**Comment by jonhenrikaavitsland** [comment]
@TGBAKC I left comments for you in your PR.
When you pick a new task, assign yourself to it so that it is your domain to work on :) 
Other than that, if you need help, you can ask @AutopsyTurvy  or the team directly in the chat as you know already. 
This task is now closed.

**Comment by AutopsyTurvy** [comment]
Thank you @jonhenrikaavitsland you’ve been wonderful 👏🏻
