### ISSUE TITLE
Create the "Settings" dropdown menu

### ISSUE THREAD

**Issue by ttowntom** [NoroffFEU/yeetsheet#164]
Create the "Settings" dropdown menu.

Screenshot from Figma:
![Image](https://github.com/user-attachments/assets/666c817a-65d6-4945-ae92-d9584f5a5d82)

**Comment by jonhenrikaavitsland** [comment]
@aklevjer good work. 
The PR was merged successfully. 
This ticket is now closed.
Thank you.
