### ISSUE TITLE
Active cell border color

### ISSUE THREAD

**Issue by ttowntom** [NoroffFEU/yeetsheet#165]
The active cell's border color should be pink.

Screenshot from Figma:
![Image](https://github.com/user-attachments/assets/347b11ce-e2ce-4b8d-9f4e-778d99efd5d1)

**Comment by thislily** [comment]
Should be working now https://github.com/NoroffFEU/yeetsheet/pull/188

**Comment by Barvand** [comment]
@thislily This is done right? I will put it under review!

Thanks,
Bart

**Comment by thislily** [comment]
Yes!  It was in review on Friday, I'm not sure what happened?
