### ISSUE TITLE
Improve toolbar responsiveness

### ISSUE THREAD

**Issue by ttowntom** [NoroffFEU/yeetsheet#182]
The toolbar takes up a lot space, and thus is moving the main part of the app - the sheet - a long ways down on mobile.
 
-  Improve the mobile experience of the toolbar

Screenshot of current toolbar in mobile view:
![Image](https://github.com/user-attachments/assets/9015390e-8c36-4b51-96cc-1e11b35c0ed3)

**Comment by karlwoien** [comment]
Hi @FredrikMohag!
I have made modifications to improve the responsiveness and layout. The changes can be viewed in PR #226
