### ISSUE TITLE
Improve Dropdowns in Header

### ISSUE THREAD

**Issue by sulenchy** [NoroffFEU/yeetsheet#192]
**User Story**

As a user, I want the dropdown menus in the header to be improved so that only one can be open at a time, preventing multiple dropdowns from being open simultaneously and enhancing the user experience.

**Acceptance Criteria:**

When a dropdown menu is opened, any previously open dropdown should automatically close.
Only one dropdown menu should be open at any given time.
The behavior should apply to all dropdowns in the header.
Ensure smooth transitions and responsiveness across devices and screen sizes.

**Comment by jonhenrikaavitsland** [comment]
@martinsk91 The PR merged successfully. 
Good wrok. 
Thank you. 
This ticket is now closed
