### ISSUE TITLE
Manage Columns and Rows in the Sheet

### ISSUE THREAD

**Issue by sulenchy** [NoroffFEU/yeetsheet#199]
**User Story:**

As a user, I want the ability to add or delete columns and rows within the sheet so that I can modify the structure of the sheet as needed for better organization and data management.

**Acceptance Criteria:**

- Users can add a new column to the sheet at any position.
- Users can delete an existing column from the sheet without affecting other columns.
- Users can add a new row to the sheet at any position.
- Users can delete an existing row from the sheet without affecting other rows.
- After adding or deleting columns or rows, the data remains intact and properly aligned.
- There are clear options (e.g., buttons or context menus) for adding and deleting columns/rows.

**Comment by ttowntom** [comment]
Screenshot from Figma file:
![Image](https://github.com/user-attachments/assets/2d542b90-ad29-44ce-a912-067f3b4c121b)
