### ISSUE TITLE
Style scroll bars

### ISSUE THREAD

**Issue by ttowntom** [NoroffFEU/yeetsheet#203]
Style the srollbars to match the design in light and dark mode.

![Image](https://github.com/user-attachments/assets/0d4b10b4-b1b2-4254-af1d-b93b5cf4cdcf)
![Image](https://github.com/user-attachments/assets/8341f987-19e8-40c4-b94f-241b7ccd5c0e)

**Comment by jonhenrikaavitsland** [comment]
@robfil50219 Apparently the Scrum Masters has decided to split up areas of responsibility. 
Pick a different task related to the header section please. 

@AutopsyTurvy We have not been informed by you about this?

**Comment by AutopsyTurvy** [comment]
@jonhenrikaavitsland , you’re right- you weren’t informed by me about it- it’s the first I’ve heard.
I’ll try to read all I can when I’m finally back.

**Comment by jonhenrikaavitsland** [comment]
@AutopsyTurvy ok, please inform the team when you can
