### ISSUE TITLE
When hovering over a cell, the cell is highlighted (HEX 55 51 63 - RGB 85, 81, 99)

### ISSUE THREAD

**Issue by jonhenrikaavitsland** [NoroffFEU/yeetsheet#209]
added hover effect in to cell input

**Comment by jonhenrikaavitsland** [comment]
@AutopsyTurvy Why is this ticket in review and why did you assign me and tugba? 
I am trying to understand what is up with this ticket?

**Comment by AutopsyTurvy** [comment]
Hello lovely-
She said she’d completed it and put it through for review,
I asked if she’d done a pull request and she said yes-
Was it not done? X

**Comment by jonhenrikaavitsland** [comment]
@AutopsyTurvy You created this ticket 3 hours ago, i dont have a PR for this. 
There was no issue created either. 
It is better if the Dev can create a PR and then request my review. 
The dev can put the ticket "in review" them selves. 
Are you saying that Tugba has been online the past couple hours and done this task? :)

**Comment by jonhenrikaavitsland** [comment]
@TGBAKC Hi, do you have a PR  for this ticket?

**Comment by jonhenrikaavitsland** [comment]
@TGBAKC @AutopsyTurvy I found the PR, it was already merged by the Dev. 
This should not happen. My review should be asked for when you get a PR. 
You should not fix your merge conflicts before my review. 
This ticket is now closed. 
A nother ticket was made to clean up.

**Comment by jonhenrikaavitsland** [comment]
@AutopsyTurvy You may have to create a new ticket for this.

**Comment by AutopsyTurvy** [comment]
@jonhenrikaavitsland I’ll create one as soon as I can.
