### ISSUE TITLE
When you click on a number, it highlights the corresponding row, when you click on a letter, it highlights the column.

### ISSUE THREAD

**Issue by renahashimi** [NoroffFEU/yeetsheet#227]
Functionality to highlight a row or column by clicking on the number or letter connected to it.
Perhaps should be able to click and highlight both a row and a column at the same time

**Comment by jonhenrikaavitsland** [comment]
@renahashimi The PR merged successfully. 
Good work. 
Thank you. 
This ticket is now closed
