### ISSUE TITLE
Change hamburger dropdown width

### ISSUE THREAD

**Issue by DanielEkerhovd** [NoroffFEU/yeetsheet#239]
Make the width of the hamburger menu more presentable: 

- Currently 100%
- Try something else!

**Comment by RamonaXR** [comment]
@DanielEkerhovd Thank you, I will work on this!

**Comment by jonhenrikaavitsland** [comment]
@RamonaXR The PR merged successfully. 
Good work. 
This ticket is now closed. 
Thank you :)
