### ISSUE TITLE
Update zoom choices

### ISSUE THREAD

**Issue by DanielEkerhovd** [NoroffFEU/yeetsheet#240]
Work on the zoom visuals on the header. 

- Currently no logic to order, change this (low-high?)
- No visuals on selected zoom value

NOTE: 
You do not need to create function on custom, as this is a larger task.

**Comment by jonhenrikaavitsland** [comment]
@renahashimi PR merged successfully. 
Good Work. 
This ticket is now closed. 
Thank you,
