### ISSUE TITLE
Create custom zoom choice functionality

### ISSUE THREAD

**Issue by DanielEkerhovd** [NoroffFEU/yeetsheet#241]
Custom zoom has currently no value function, implement this: 

- When custom choice is pressed, an input value is created to input own zoom choice
- Return the inputted value

You do not need to create a function to implement this to the cell section, but lay the fundamentals for it to be implemented later.

**Comment by jonhenrikaavitsland** [comment]
@DanielEkerhovd I think Team Røyskatt has implemented this
