### ISSUE TITLE
Fix dropdown bug

### ISSUE THREAD

**Issue by DanielEkerhovd** [NoroffFEU/yeetsheet#247]
Dropdown hamburger menu does not work after update: 

- All md: classes in dropdown menu has to be changed to lg:

See image:

![Image](https://github.com/user-attachments/assets/b1933e1b-b711-47e3-9720-d7603a6a1ea5)

**Comment by jonhenrikaavitsland** [comment]
@aklevjer PR merged successfully. 
This ticket is now closed. 
Thank you.
