### ISSUE TITLE
Fix navbar placement

### ISSUE THREAD

**Issue by DanielEkerhovd** [NoroffFEU/yeetsheet#274]

**Comment by DanielEkerhovd** [comment]
The navbar is aligned on the right. Figma file is showing in on the left. 

![Image](https://github.com/user-attachments/assets/b0f595fc-3070-4dd9-ad1b-509610f1962a)

Remove justify end on line 58
![Image](https://github.com/user-attachments/assets/5486a68e-be57-495b-b620-5b312b240f19)

**Comment by jonhenrikaavitsland** [comment]
@renahashimi @DanielEkerhovd This has already been fixed by ticket #270.
The PR was not implemented as the other one did exactly the same.
Good work anyways.
Thank you for the contribution. 
This ticket is closed.
