### ISSUE TITLE
Implement eval() function

### ISSUE THREAD

**Issue by petternikolai** [NoroffFEU/yeetsheet#30]
Contact Kristian Hagesaeter before starting on this task. 
You are going to create a sub branch of Kristian's branch to avoid conflict and repetision.

Take a look at those concepts: 

-Web Workers - new Worker('worker.js');
-Limiting scope while doing eval (see example below)

```
function safeEval(code, context = {}) {
    const contextKeys = Object.keys(context);
    const contextValues = contextKeys.map(key => context[key]);
    const wrappedCode = `
        (function(${contextKeys.join(', ')}) {
            return eval(${JSON.stringify(code)});
        })(...arguments)
    `;
    try {
        return (new Function(wrappedCode))(...contextValues);
    } catch (error) {
        return `Error: ${error.message}`;
    }
}
// Example usage
const result = safeEval('a + b', { a: 1, b: 2 });
```

**Comment by petternikolai** [comment]
I am not sure what I'm expected to do here and I've tried working it out but without any luck.

**Comment by WeronikaMartinsen** [comment]
https://www.loom.com/share/1a926c64a00949de944b463f5ca48b5d?sid=03c88b3d-3bbd-4def-9a1d-7b53eabe0f4d

Here is walk througth the Eval() function made by Oliver. Please, take a look.

**Comment by jonlar93** [comment]
@sulenchy  i am working on the code editor at the moment. and do i need to add safe eval() or can i simply run the code from the editor in eval? 
is there a reason to add the security and complexity around safe eval() either trough scope limiting or multithreading?
when it seems like the only data you can access with it is your own data at this moment.

i see the code from this ticket and pull request dont exsist in our currenct workflow branch
