### ISSUE TITLE
User experience: Dropdown menu 

### ISSUE THREAD

**Issue by LillKonst** [NoroffFEU/yeetsheet#52]
Tested on Netlify app: https://yeetsheet.netlify.app/ (05.06 8:30)

The "File" dropdown menu in the header only closes when you click "File" again. This is not necessarily intuitive because the "File" button does not change when clicked. It would be nice if the dropdown menu close whenever clicked outside the menu, has a close button or the "File" button looks activated. 

Steps to reproduce

Open the application
Click on "File" 
Observe if there is an intuitive way to close the menu.

Expected Result:

The dropdown menu should be able to close easily. 
Actual Result:

The dropdown menu was confusing to close.

**Comment by Krihag** [comment]
Hello. @Anne-Serine added a solution for this that was pushed not to long ago. It should now close if you click anywhere on the screen that is not inside of the opened menu. Is this a good enough solution?

**Comment by LillKonst** [comment]
Yes, perfect!
