### ISSUE TITLE
Ability to import and export csv/json file into yeetsheet

### ISSUE THREAD

**Issue by sulenchy** [NoroffFEU/yeetsheet#84]
The ticket involves implementing the import and export functionality. Here is the acceptance criteria:
As a user,
I want to import a valid CSV or JSON file,
So that I can load the file's data into a new sheet in Yeetsheet.

Acceptance Criteria:
Scenario: User clicks "Import existing file"

Given I am on the file import page,
When I click the "Import existing file" button,
Then I should see a dialog box prompting me to select a file.
Scenario: User selects a CSV or JSON file for import

Given the file selection dialog box is open,
When I select a valid CSV or JSON file and click "Import",
Then the file's data should render in a new sheet within Yeetsheet.
Scenario: Unsupported file type is selected

Given I have selected a file that is not a CSV or JSON,
When I attempt to import the file,
Then I should see an error message indicating that only CSV or JSON files are supported.

Here is the existing PR #189. Note that you are not mandatory to use the existing code. You can overwrite the changes with your solution.

**Comment by jonhenrikaavitsland** [comment]
@RamonaXR We will look further into this tomorrow. 
Work on something else until then if you have time.

**Comment by RamonaXR** [comment]
@jonhenrikaavitsland Ok, I will work on the next ticket while I wait.

**Comment by jonhenrikaavitsland** [comment]
@RamonaXR I have requested for some conflicts to be resolved in the PR

**Comment by RamonaXR** [comment]
@jonhenrikaavitsland Ok. Will look into it.

**Comment by jonhenrikaavitsland** [comment]
@RamonaXR the PR merged successfully. 
This ticket is now closed. 
Thank you

**Comment by jonhenrikaavitsland** [comment]
@RamonaXR The PR casued issues with the page and had to be reverted. 
This is unfortunate, but we will have to work on it further next tomorrow or next week. 
This ticket is reopened.

**Comment by RamonaXR** [comment]
@jonhenrikaavitsland The never ending ticket 😂

**Comment by jonhenrikaavitsland** [comment]
@RamonaXR  This was merged afterall. 
Thank you :)

**Comment by sulenchy** [comment]
@RamonaXR and @jonhenrikaavitsland I just reverted the most important file from the lost PR to a new PR. Now, you have the most recent file changes.

**Comment by jonhenrikaavitsland** [comment]
@RamonaXR @sulenchy PR merged successfully, ticket has been closed.
